# compute_environment: LOCAL_MACHINE
# debug: true
# deepspeed_config:
#   deepspeed_config_file: configs/deep_sp_rl_finetuning_config.json
#   zero3_init_flag: false
# distributed_type: DEEPSPEED
# downcast_bf16: 'no'
# dynamo_config:
#   dynamo_backend: INDUCTOR
# machine_rank: 0
# main_training_function: main
# num_machines: 1
# num_processes: 4
# rdzv_backend: static
# same_network: true
# tpu_env: []
# tpu_use_cluster: false
# tpu_use_sudo: false
# use_cpu: false

command_file: null
commands: null
compute_environment: LOCAL_MACHINE
# deepspeed_config:
#   deepspeed_config_file: configs/deep_sp_rl_finetuning_config
#   zero3_init_flag: false
# distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_config: {}
fsdp_config: {}
gpu_ids: null
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
megatron_lm_config: {}
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_name: null
tpu_zone: null
use_cpu: false